- name: Assure workspace existence
  file:
    path: "{{ installation_workspace }}/{{ code_install_path }}"
    state: directory

- name: Set install_package scripts
  template:
    src: install_package.sh.j2
    dest: "{{ installation_workspace }}/{{ code_install_path }}/install_package.sh"
    mode: '0755'

- name: Set  gcp-images scripts
  template:
    src: gcp-images.sh.j2
    dest: "{{ installation_workspace }}/{{ code_install_path }}/gcp-images.sh"
    mode: '0755'

- name: Set manual scripts
  template:
    src: manual.sh.j2
    dest: "{{ installation_workspace }}/{{ code_install_path }}/manual.sh"
    mode: '0755'

- name: Set install scripts
  template:
    src: install.sh.j2
    dest: "{{ installation_workspace }}/{{ code_install_path }}/install.sh"
    mode: '0755'

- name: Copy gitlab data
  copy:
    src: "{{ code_binary_dir }}/gitlab_data.tar"
    dest: "{{ installation_workspace }}/{{ code_install_path }}/gitlab_data.tar"

- name: Set Docker Compose
  copy:
    src: "{{ code_conf_dir }}/docker-compose.yml"
    dest: "{{ installation_workspace }}/{{ code_install_path }}/docker-compose.yml"

- name: Exec manual
  shell: |
    sh manual.sh
  args:
    chdir: "{{ installation_workspace }}/{{ code_install_path }}"
    executable: /bin/bash

















