version: '3.0'
services:
  mysql:
    image: ${LC_REGISTRY}/cloudos/haier/mysql:RC4.23.2
    container_name: ${DB_CONTAINER}
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ${DB_VOLUME}:/var/lib/mysql
    environment:
      MYSQL_USER_DATABASE: service_user
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  rabbitmq:
    image: ${LC_REGISTRY}/cloudtogo/rabbitmq:3.7-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${ENV_RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${ENV_RABBITMQ_PASSWORD}

