- name: Assure workspace existence
  file:
    path: "{{ installation_workspace }}/{{ infra_install_path }}"
    state: directory

- name: Set  common gcp-images scripts
  template:
    src: "{{ common_file_path }}/gcp-images.sh"
    dest: "{{ installation_workspace }}/{{ infra_install_path }}/gcp-images.sh"
    mode: '0755'

- name: Set  common install_package scripts
  template:
    src: "{{ common_file_path }}/install_package.sh"
    dest: "{{ installation_workspace }}/{{ infra_install_path }}/install_package.sh"
    mode: '0755'

- name: Set env scripts
  template:
    src: env.sh.j2
    dest: "{{ installation_workspace }}/{{ infra_install_path }}/env.sh"
    mode: '0755'

- name: Set manual scripts
  template:
    src: manual.sh.j2
    dest: "{{ installation_workspace }}/{{ infra_install_path }}/manual.sh"
    mode: '0755'

- name: Set install scripts
  template:
    src: install.sh.j2
    dest: "{{ installation_workspace }}/{{ infra_install_path }}/install.sh"
    mode: '0755'

- name: Assure conf.d existence
  file:
    path: "{{ installation_workspace }}/{{ infra_install_path }}/conf.d"
    state: directory

- name: Set default conf
  template:
    src: default.conf.j2
    dest: "{{ installation_workspace }}/{{ infra_install_path }}/conf.d/default.conf"

- name: Set promxy
  copy:
    src: "{{ infra_conf_dir }}/promxy.yaml"
    dest: "{{ installation_workspace }}/{{ infra_install_path }}/promxy.yaml"

- name: Set Docker Compose
  copy:
    src: "{{ infra_conf_dir }}/docker-compose.yml"
    dest: "{{ installation_workspace }}/{{ infra_install_path }}/docker-compose.yml"

- name: Exec manual
  shell: |
    sh manual.sh
  args:
    chdir: "{{ installation_workspace }}/{{ infra_install_path }}"
    executable: /bin/bash

